prometheusOperator:
    nodeSelector:
        kubernetes.io/arch: amd64
    admissionWebhooks:
        patch:
            nodeSelector:
                kubernetes.io/arch: amd64
        nodeSelector:
            kubernetes.io/arch: amd64
grafana:
    nodeSelector:
        kubernetes.io/arch: amd64
alertmanager:
    alertmanagerSpec:
        nodeSelector:
            kubernetes.io/arch: amd64
prometheus:
    prometheusSpec:
        nodeSelector:
            kubernetes.io/arch: amd64