# Base environment variables common across all functions
environment:
  TARGET_BASE_URL: wio-mock.default.svc
  TARGET_BASE_PORT: 8080
  TARGET_METRIC_GROUP: mock-metrics
  PROMETHEUS_HOST: http://metrics-sink-prometheus-pushgateway.default.svc